### ISSUE TITLE
Dev server: "Server communication error" - Add a mock server for api calls

### ISSUE THREAD

**Issue by ptandler** [Swing-team/pendulums-web-client#53]
The readme says "Run `npm run start` for a dev server"

However, when I run this and try to create an account, I see the message "Server communication error" and a POST request to `http://localhost:1337/auth/signup` that fails.

This looks to me that there should be some kind of backend running locally which isn't started together with ng serve.

So my question is: What do I have to do to get this up and running to be able to start development?

**Comment by arminghm** [comment]
@ptandler thanks for chipping in 👍.
The backend is not an open source project.
I'll add a mock server with some data to be used for api calls responses.

**Comment by ptandler** [comment]
Hm, why's the backend not open source as well? I wasn't aware.
What's the point of having an open source client, while my data is still stored in a proprietary system?
Maybe I'm missing something here ...? So I would be glad if you could explain.

**Comment by mohammadrafigh** [comment]
At first thanks for your interest in Pendulums. Many platforms and applications have open source clients but they keep their backend services closed source for different reasons. Currently Pendulums is a free software with no hidden costs and just relies on donations. We don't sell our users data to other companies and organizations, we don't show any ads and there is no premium plans yet (we are thinking about this one). So we kept the backend closed source because there are some chances to sell our self-hosted solutions to companies and organizations. Maybe some day we separate our community edition app/backend so we can open source all of these.
We are preparing a mock server which would be available in a few days.
Feel free if you have more questions.

**Comment by mohammadrafigh** [comment]
@ptandler today we deployed an alpha version of our backend for test and development purposes, so feel free to use it instead of a mock server. You can expect the same behavior between production and development. to use the alpha server please edit `src/environments/local.config.ts` and use these property/value pairs:

```
  // app configs
  socketEndpoint: 'https://alpha.pendulums.io',
  socketPath: '/api/socket.io',
  apiEndpoint: 'https://alpha.pendulums.io/api',
  httpOptions: { withCredentials: true, responseType: 'json' },
  imagesEndpoint: 'https://alpha.pendulums.io/api/images',
```

to make these changes permanent in your development environment edit `prepare.js` file as well.
I close this issue feel free to re-open it if you have any problems :+1:
